//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCNetConfig.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCNetConfig.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ccnet.config file not found in {0} 的本地化字符串。
        /// </summary>
        internal static string ConfigFileNotFoundMessage {
            get {
                return ResourceManager.GetString("ConfigFileNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration Version: {0} 的本地化字符串。
        /// </summary>
        internal static string ConfigVersionStatusLabelFormat {
            get {
                return ResourceManager.GetString("ConfigVersionStatusLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Manually edit config file|&amp;Report Errors as a Bug 的本地化字符串。
        /// </summary>
        internal static string ConfigXmlErrorsCommandButtons {
            get {
                return ResourceManager.GetString("ConfigXmlErrorsCommandButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error loading the XML configuration file. The following error occured: {0} 的本地化字符串。
        /// </summary>
        internal static string ConfigXmlErrorsMessage {
            get {
                return ResourceManager.GetString("ConfigXmlErrorsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XMLConfiguration Erorrs 的本地化字符串。
        /// </summary>
        internal static string ConfigXmlErrorsTitle {
            get {
                return ResourceManager.GetString("ConfigXmlErrorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete all of your backup files? 的本地化字符串。
        /// </summary>
        internal static string ConfirmDeleteBackupsMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteBackupsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Delete 的本地化字符串。
        /// </summary>
        internal static string ConfirmDeleteBackupsTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteBackupsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete the selected backup files? 的本地化字符串。
        /// </summary>
        internal static string ConfirmDeleteSelectedBackupsMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteSelectedBackupsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy{1} of {0} 的本地化字符串。
        /// </summary>
        internal static string CopyOfProject {
            get {
                return ResourceManager.GetString("CopyOfProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy {0} As... 的本地化字符串。
        /// </summary>
        internal static string CopyProjectAsMenuItem {
            get {
                return ResourceManager.GetString("CopyProjectAsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy {0} 的本地化字符串。
        /// </summary>
        internal static string CopyProjectMenuItem {
            get {
                return ResourceManager.GetString("CopyProjectMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;View errors in config file|&amp;Manually edit config file|&amp;Ignore Errors and continue load 的本地化字符串。
        /// </summary>
        internal static string ErrorLoadingConfigFileCommandButtons {
            get {
                return ResourceManager.GetString("ErrorLoadingConfigFileCommandButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error while loading the configuration file. 的本地化字符串。
        /// </summary>
        internal static string ErrorLoadingConfigFileMessage {
            get {
                return ResourceManager.GetString("ErrorLoadingConfigFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Loading Configuration File 的本地化字符串。
        /// </summary>
        internal static string ErrorLoadingConfigFileTitle {
            get {
                return ResourceManager.GetString("ErrorLoadingConfigFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Abort Save|Retry &amp;Saving the file|&amp;Report Error as a Bug 的本地化字符串。
        /// </summary>
        internal static string ErrorSavingCommandButtons {
            get {
                return ResourceManager.GetString("ErrorSavingCommandButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error while attempting to save the configuration file:
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string ErrorSavingMessage {
            get {
                return ResourceManager.GetString("ErrorSavingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Saving Configuration 的本地化字符串。
        /// </summary>
        internal static string ErrorSavingTitle {
            get {
                return ResourceManager.GetString("ErrorSavingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Not Found 的本地化字符串。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;/?[^&gt;]*&gt; 的本地化字符串。
        /// </summary>
        internal static string HtmlRegexPattern {
            get {
                return ResourceManager.GetString("HtmlRegexPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CCNet Configuration|ccnet.config|Configuration Files|*.config|XML Files|*.xml|All Files|*.* 的本地化字符串。
        /// </summary>
        internal static string OpenSaveFilter {
            get {
                return ResourceManager.GetString("OpenSaveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose a &amp;different name|&amp;Cancel new project 的本地化字符串。
        /// </summary>
        internal static string ProjectNameExistsCommandButtons {
            get {
                return ResourceManager.GetString("ProjectNameExistsCommandButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A project with that name already exists, what would you like to do? 的本地化字符串。
        /// </summary>
        internal static string ProjectNameExistsMessage {
            get {
                return ResourceManager.GetString("ProjectNameExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Name Exists 的本地化字符串。
        /// </summary>
        internal static string ProjectNameExistsTitle {
            get {
                return ResourceManager.GetString("ProjectNameExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Save As New File|&amp;Remove Readonly Flag and Save|&amp;Cancel Save 的本地化字符串。
        /// </summary>
        internal static string ReadonlyFileCommandButtons {
            get {
                return ResourceManager.GetString("ReadonlyFileCommandButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The currently opened configuration file you are trying to save is marked readonly. What would you like to do? 的本地化字符串。
        /// </summary>
        internal static string ReadonlyFileMessage {
            get {
                return ResourceManager.GetString("ReadonlyFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration File is readonly 的本地化字符串。
        /// </summary>
        internal static string ReadonlyFileTitle {
            get {
                return ResourceManager.GetString("ReadonlyFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to save configuration. 的本地化字符串。
        /// </summary>
        internal static string UnableToSaveConfiguration {
            get {
                return ResourceManager.GetString("UnableToSaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Info-ZIP License 的本地化字符串。
        /// </summary>
        internal static string UnzipLicenseText {
            get {
                return ResourceManager.GetString("UnzipLicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updates are available for {1}. Click &apos;Update Now&apos; below to update to version {0}. 的本地化字符串。
        /// </summary>
        internal static string UpdatesAvailableMessage {
            get {
                return ResourceManager.GetString("UpdatesAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version Not Selected. 的本地化字符串。
        /// </summary>
        internal static string VersionNotSelected {
            get {
                return ResourceManager.GetString("VersionNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a version before continuing. 的本地化字符串。
        /// </summary>
        internal static string VersionNotSelectedMessage {
            get {
                return ResourceManager.GetString("VersionNotSelectedMessage", resourceCulture);
            }
        }
    }
}
