//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCNetConfig.Updater.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCNetConfig.Updater.Core.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ^[&apos;&quot;]?(.*?)[&apos;&quot;]?$ 的本地化字符串。
        /// </summary>
        internal static string ArgumentsRemoverRegex {
            get {
                return ResourceManager.GetString("ArgumentsRemoverRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^-{1,2}|^/|=|: 的本地化字符串。
        /// </summary>
        internal static string ArgumentsSplitterRegex {
            get {
                return ResourceManager.GetString("ArgumentsSplitterRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update 的本地化字符串。
        /// </summary>
        internal static string UpdateInfoNamespacePrefix {
            get {
                return ResourceManager.GetString("UpdateInfoNamespacePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //{0}:UpdateInfo 的本地化字符串。
        /// </summary>
        internal static string UpdateInfoRootXPath {
            get {
                return ResourceManager.GetString("UpdateInfoRootXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to load configuration file. 的本地化字符串。
        /// </summary>
        internal static string UpdaterConfigLoadErrorMessage {
            get {
                return ResourceManager.GetString("UpdaterConfigLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data\UpdaterConfiguration.config 的本地化字符串。
        /// </summary>
        internal static string UpdaterConfigurationFile {
            get {
                return ResourceManager.GetString("UpdaterConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CCNetConfigApplicationUpdater 的本地化字符串。
        /// </summary>
        internal static string UpdaterTempPathFolder {
            get {
                return ResourceManager.GetString("UpdaterTempPathFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CCNetConfig Updater Version {0} - http://ccnetconfig.org 的本地化字符串。
        /// </summary>
        internal static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
    }
}
